{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devicemanifest-solution-b.fullname" . }}-api-secret
  labels:
    {{- include "devicemanifest-solution-b.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.api.config.minio.accessKey }}
  secretKey: {{ .Values.api.config.minio.secretKey }}
{{- end }}
